### ISSUE TITLE
[FEATURE REQUEST] Name generation without sex

### ISSUE THREAD

**Issue by wiploo** [ironarachne/muna#2]
Hi @BenOvermyer, thank for your fantastic script.

Most of the name generated by this script are suitable for male/female. I need only random name, sex is not important. 

Is there a way to ask the generation of random name male/female without the need to make two call and mix them together?

Best Regards

**Comment by BenOvermyer** [comment]
OK, this is done.

I also deployed it.

You can use this new feature via the `given` keyword:

https://names.ironarachne.com/race/dwarf/given/10

**Comment by wiploo** [comment]
Wow, fantastic. Many thanks!
